- title: GitHub
  id: github
  name: "model-definitions/github"
  uid: 909c3278-f7d1-461c-9352-87741bef11d3
  documentationUrl: https://docs.instill.tech/integrations/models/http
  icon: http.svg
  model_spec: 
      repo: 
  model_instance_spec: 
      repo: 
      tag:        
- title: Local
  id: local
  name: "model-definitions/local"
  uid: 909c3278-f7d1-461c-9352-87741bef1abc
  documentationUrl: https://docs.instill.tech/integrations/models/http
  icon: http.svg
  model_spec: 
      repo: 
  model_instance_spec: 
      repo: 
      tag: 