FROM loadimpact/k6:latest AS k6official

FROM --platform=$BUILDPLATFORM golang:1.18.2

ARG SERVICE_NAME

COPY --from=k6official /usr/bin/k6 /usr/bin/k6

WORKDIR /${SERVICE_NAME}
COPY . /${SERVICE_NAME}

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go install github.com/cosmtrek/air@latest

RUN apt-get update
RUN apt-get -y install python3 python3-setuptools python3-pip git git-lfs
RUN pip install --upgrade pip setuptools wheel
RUN pip3 install --no-cache-dir transformers==4.21.0 pillow torch==1.12.1 torchvision==0.13.1 onnxruntime==1.11.1 dvc[gs]==2.34.2

ENTRYPOINT ["tail", "-f", "/dev/null"]
