name: "pre"
backend: "python"
max_batch_size: 16
input [
  {
    name: "input"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
dynamic_batching { }
version_policy: { all { }}
parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "/conda-pack/python-3-8.tar.gz"}
}