BEGIN;

ALTER TYPE valid_task ADD VALUE 'TASK_CHAT';
ALTER TYPE valid_task ADD VALUE 'TASK_COMPLETION';
ALTER TYPE valid_task ADD VALUE 'TASK_EMBEDDING';
ALTER TYPE valid_task ADD VALUE 'TASK_CUSTOM';

COMMIT;
