BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;
ALTER TABLE model ADD COLUMN IF NOT EXISTS namespace_id VARCHAR(255) DEFAULT '';
ALTER TABLE model ADD COLUMN IF NOT EXISTS namespace_type VARCHAR(255) DEFAULT '';

COMMIT;
