BEGIN;

ALTER TYPE valid_task ADD VALUE 'TASK_CHAT';
ALTER TYPE valid_task ADD VALUE 'TASK_COMPLETION';
ALTER TYPE valid_task ADD VALUE 'TASK_EMBEDDING';
ALTER TYPE valid_task ADD VALUE 'TASK_CUSTOM';

COMMIT;

UPDATE model SET task = 'TASK_CHAT' WHERE task = 'TASK_TEXT_GENERATION_CHAT';
UPDATE model SET task = 'TASK_CHAT' WHERE task = 'TASK_VISUAL_QUESTION_ANSWERING';
UPDATE model SET task = 'TASK_COMPLETION' WHERE task = 'TASK_TEXT_GENERATION';

COMMIT;
