BEGIN;

ALTER TABLE "model"
ADD COLUMN IF NOT EXISTS "provider" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "region" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "hardware" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "github" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "link" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "license" VARCHAR(255),
ADD COLUMN "readme" TEXT DEFAULT '';

CREATE TABLE IF NOT EXISTS "model_version" (
    "uid" UUID PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "id" VARCHAR(255) NOT NULL,
    "digest" VARCHAR(255) NOT NULL,
    "create_time" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "update_time" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "delete_time" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL,
    "model_uid" UUID NOT NULL,
    CONSTRAINT fk_model_uid
    FOREIGN KEY ("model_uid")
    REFERENCES model ("uid")
    ON DELETE CASCADE
);
