- id: "github"
  uid: "909c3278-f7d1-461c-9352-87741bef11d3"
  title: "GitHub"
  documentationUrl: "https://www.instill.tech/docs/import-models/github"
  icon: "github.svg"
  releaseStage: alpha
  modelSpec:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "GitHub Model"
    type: "object"
    required:
      - "repository"
      - "tag"
    instillShortDescription: ""
    additionalProperties: false
    minProperties: 2
    maxProperties: 3
    properties:
      repository:
        type: "string"
        title: "GitHub repository"
        description: "The name of a public GitHub repository, e.g. `instill-ai/model-yolov7`."
        instillUIComponent: "textfield"
        examples:
          - "instill-ai/model-yolov7"
          - "instill-ai/model-mobilenetv2"
        instillUIOrder: 0
        minLength: 0
        maxLength: 1023
      tag:
        type: "string"
        title: "GitHub repository tag"
        description: "The tag of the GitHub repository, e.g., `v0.1.0`."
        instillUIComponent: "textfield"
        examples:
          - "v0.1.0-alpha"
          - "v1.0.0"
        instillUIOrder: 1
        minLength: 0
        maxLength: 200
- id: "local"
  uid: "96b547c2-8927-43ca-a0cd-a72306621696"
  title: "Local"
  documentationUrl: "https://www.instill.tech/docs/import-models/local"
  icon: "local.svg"
  releaseStage: alpha
  modelSpec:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "Local Model"
    type: "object"
    required:
      - "content"
    instillShortDescription: ""
    additionalProperties: false
    minProperties: 1
    maxProperties: 1
    properties:
      content:
        type: "string"
        instillUIComponent: "file_upload"
        title: "Upload a .zip file"
        description: "Create and upload a zip file that contains all the model files from your computer. We recommend you add a README.md file in the root directory to describe the model in details."
        instillUIOrder: 0
        minLength: 0
        maxLength: 1023
- id: "container"
  uid: "3b4265b7-7d8c-42f7-b5a9-13737d7dee1d"
  title: "Container"
  documentationUrl: "https://www.instill.tech/docs/import-models/local"
  icon: "local.svg"
  releaseStage: alpha
  modelSpec:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "Containerized Model"
    type: "object"
    required:
      - "task"
      - "gpu"
    instillShortDescription: ""
    additionalProperties: false
    minProperties: 2
    maxProperties: 2
    properties:
      task:
        type: "string"
        instillUIComponent: "textfield"
        title: "Enter your model's Instill Task"
        description: "Create and upload a containerized model which uses this Instill Task."
        instillUIOrder: 0
        minLength: 0
        maxLength: 1023
      gpu:
        type: "boolean"
        instillUIComponent: "boolean"
        title: "If your model needs to run on GPU"
        description: "Select whether your model needs to run on GPU or not"
        instillUIOrder: 1
        minLength: 0
        maxLength: 1023
