- id: "github"
  uid: "909c3278-f7d1-461c-9352-87741bef11d3"
  title: "GitHub"
  documentationUrl: "https://docs.instill.tech/models/definitions/github"
  icon: "github.svg"
  modelSpec:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "GitHub spec for model"
    type: "object"
    required:
    - "repository"
    additionalProperties: false
    properties:
      repository:
        type: "string"
        title: "GitHub repository"
        description: "The name of a public GitHub repository, e.g. `instill-ai/yolov4`."
        examples:
        - "instill-ai/yolov4"
        - "instill-ai/mobilenetv2"
        ui_order: 0
        ui_component: "text"
      html_url:
        type: "string"
        title: "Github repository URL"
        description: "The URL of the GitHub repository, e.g. `https://github.com/instill-ai/yolov4`"
        examples:
        - "https://github.com/instill-ai/yolov4"
        - "https://github.com/instill-ai/mobilenetv2"
        readOnly: true
        ui_order: 1
        ui_hidden: true
        ui_disabled: true
        ui_component: "text"
  modelInstanceSpec:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "GitHub spec for model instance"
    type: "object"
    required:
    - "repository"
    - "tag"
    additionalProperties: false
    properties:
      repository:
        type: "string"
        title: "GitHub repository"
        description: "The name of a public GitHub repository, e.g. `instill-ai/yolov4`."
        examples:
        - "instill-ai/yolov4"
        - "instill-ai/mobilenetv2"
        readOnly: true
        ui_order: 0
        ui_disabled: true
        ui_component: "text"
      tag:
        type: "string"
        title: "GitHub repository"
        description: "Tag of the GitHub repository, e.g., `v0.1.0`."
        examples:
        - "v0.1.0-alpha"
        - "v1.0.0"
        readOnly: true
        ui_order: 1
        ui_disabled: true
        ui_component: "text"
      html_url:
        type: "string"
        title: "Github repository URL"
        description: "GitHub repository URL, e.g., `https://github.com/instill-ai/yolov4/tree/v1.0.0`."
        examples:
        - "https://github.com/instill-ai/yolov4/tree/v0.1.0-alpha"
        - "https://github.com/instill-ai/yolov4/tree/v1.0.0"
        readOnly: true
        ui_order: 2
        ui_disabled: true
        ui_component: "text"
- id: local
  uid: "96b547c2-8927-43ca-a0cd-a72306621696"
  title: Local
  documentationUrl: "https://docs.instill.tech/models/definitions/local"
  icon: "local.svg"
  modelSpec:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "Local spec for model"
    type: "object"
    required:
    - "content"
    additionalProperties: false
    properties:
      description:
        type: "string"
        title: "Description"
        description: "Fill with a short description of your model"
        maxLength: 1023
        writeOnly: true
        ui_order: 0
        ui_component: "textarea_enable_counter"
      content:
        type: "string"
        contentMediaType: "application/zip"
        title: "Upload a .zip file"
        description: "Create and upload a zip file that contains all the model files from your computer"
        ui_order: 1
        ui_disabled: true
        ui_hidden: true
        ui_component: "file"
  modelInstanceSpec:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "Local spec for model instance"
    type: "object"
    required:
    - "content"
    additionalProperties: false
    properties:
      content:
        type: "string"
        contentMediaType: "application/zip"
        title: "Upload a .zip file"
        description: "Create and upload a zip file that contains all the model files from your computer"
        readOnly: true
        ui_order: 1
        ui_hidden: true
        ui_disabled: true
        ui_component: "file"
- id: artivc
  uid: "53c5a6de-2a33-4bf0-bef3-4de8cade2a93"
  title: ArtiVC
  documentationUrl: "https://docs.instill.tech/models/definitions/artivc"
  icon: "artivc.svg"
  modelSpec:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "ArtiVC spec for model"
    type: "object"
    required:
    - "url"
    additionalProperties: false
    properties:
      description:
        type: "string"
        title: "Description"
        description: "Fill with a short description of your model"
        maxLength: 1023
        writeOnly: true
        ui_order: 0
        ui_component: "textarea_enable_counter"
      url:
        type: "string"
        title: "Cloud storage url"
        description: "the cloud storage url, e.g. `gs://public-europe-west2-c-artifacts/vdp/public-models/yolov4`."
        examples:
        - "gs://public-europe-west2-c-artifacts/vdp/public-models/yolov4"
        - "s3://vdp/public-models/yolov4"
        readOnly: true
        ui_order: 1
        ui_component: "text"       
      credential:
        type: "object"
        title: "Credential"
        description: "credential to work with cloud storage in json object format"
        readOnly: true
        ui_order: 2
  modelInstanceSpec:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "ArtiVC spec for model instance"
    type: "object"
    required:
    - "url"
    - "tag"
    additionalProperties: false
    properties:
      url:
        type: "string"
        title: "Cloud storage url"
        description: "the cloud storage url, e.g. `gs://public-europe-west2-c-artifacts/vdp/public-models/yolov4`."
        examples:
        - "gs://public-europe-west2-c-artifacts/vdp/public-models/yolov4"
        - "s3://vdp/public-models/yolov4"
        readOnly: true
        ui_order: 0
        ui_component: "text"    
      tag:
        type: "string"
        title: "ArtiVC version"
        description: "Tag of the ArtiVC, e.g., `v0.1.0`."
        examples:
        - "v0.1.0-alpha"
        - "v1.0.0"
        readOnly: true
        ui_order: 1
        ui_disabled: true
        ui_component: "text"
- id: "huggingface"
  uid: "5b2e1d10-1fab-462d-9d6a-ba41f4b4d816"
  title: "HuggingFace"
  documentationUrl: "https://docs.instill.tech/models/definitions/huggingface"
  icon: "huggingface.svg"
  modelSpec:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "HuggingFace spec for model"
    type: "object"
    required:
    - "repo_id"
    additionalProperties: false
    properties:
      repo_id:
        type: "string"
        title: "HuggingFace model ID"
        description: "The name of a public HuggingFace model ID, e.g. `google/vit-base-patch16-224`."
        examples:
        - "google/vit-base-patch16-224"
        - "facebook/deit-base-distilled-patch16-224"
        ui_order: 0
        ui_component: "text"
      description:
        type: "string"
        title: "Description"
        description: "Fill with a short description of your model"
        maxLength: 1023
        writeOnly: true
        ui_order: 1
        ui_component: "textarea_enable_counter"        
      html_url:
        type: "string"
        title: "HuggingFace repository URL"
        description: "The URL of the HuggingFace repository, e.g. `https://huggingface.co/facebook/deit-base-distilled-patch16-224`"
        examples:
        - "https://huggingface.co/google/vit-base-patch16-224"
        - "https://huggingface.co/facebook/deit-base-distilled-patch16-224"
        readOnly: true
        ui_order: 2
        ui_hidden: true
        ui_disabled: true
        ui_component: "text"
  modelInstanceSpec:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "HuggingFace spec for model instance"
    type: "object"
    required:
    - "repo_id"
    additionalProperties: false
    properties:
      repo_id:
        type: "string"
        title: "HuggingFace model ID"
        description: "The name of a public HuggingFace model ID, e.g. `google/vit-base-patch16-224`."
        examples:
        - "google/vit-base-patch16-224"
        - "facebook/deit-base-distilled-patch16-224"
        ui_order: 0
        ui_component: "text"
      html_url:
        type: "string"
        title: "HuggingFace repository URL"
        description: "The URL of the HuggingFace repository, e.g. `https://huggingface.co/facebook/deit-base-distilled-patch16-224/tree/main`"
        examples:
        - "https://huggingface.co/google/vit-base-patch16-224/tree/main"
        - "https://huggingface.co/facebook/deit-base-distilled-patch16-224/tree/main"
        readOnly: true
        ui_order: 1
        ui_hidden: true
        ui_disabled: true
        ui_component: "text"