// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: ray/v1/ray.proto

package rayserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RayService_Trigger_FullMethodName = "/ray.v1.RayService/Trigger"
)

// RayServiceClient is the client API for RayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RayServiceClient interface {
	// Trigger method is the defaut trigger entry for ray deployment
	Trigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
}

type rayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRayServiceClient(cc grpc.ClientConnInterface) RayServiceClient {
	return &rayServiceClient{cc}
}

func (c *rayServiceClient) Trigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, RayService_Trigger_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RayServiceServer is the server API for RayService service.
// All implementations must embed UnimplementedRayServiceServer
// for forward compatibility
type RayServiceServer interface {
	// Trigger method is the defaut trigger entry for ray deployment
	Trigger(context.Context, *TriggerRequest) (*TriggerResponse, error)
	mustEmbedUnimplementedRayServiceServer()
}

// UnimplementedRayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRayServiceServer struct {
}

func (UnimplementedRayServiceServer) Trigger(context.Context, *TriggerRequest) (*TriggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trigger not implemented")
}
func (UnimplementedRayServiceServer) mustEmbedUnimplementedRayServiceServer() {}

// UnsafeRayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RayServiceServer will
// result in compilation errors.
type UnsafeRayServiceServer interface {
	mustEmbedUnimplementedRayServiceServer()
}

func RegisterRayServiceServer(s grpc.ServiceRegistrar, srv RayServiceServer) {
	s.RegisterService(&RayService_ServiceDesc, srv)
}

func _RayService_Trigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RayServiceServer).Trigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RayService_Trigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RayServiceServer).Trigger(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RayService_ServiceDesc is the grpc.ServiceDesc for RayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ray.v1.RayService",
	HandlerType: (*RayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Trigger",
			Handler:    _RayService_Trigger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ray/v1/ray.proto",
}
