server:
  port: 8080
  http:
    enabled: true
    port: 8080
  https:
    enabled: false
    port: 8445
    cert: /model-backend/ssl/tls.crt
    key: /model-backend/ssl/tls.key
  cors-origins:
    - http://localhost
    - https://instill-inc.tech
    - https://instill.tech
database:
  timezone: Etc/UTC
  username: postgres
  password: password
  host: localhost
  port: 5432
  name: model
  version: 1
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30 # In minutes
tritonserver:
  grpcuri: 0.0.0.0:8001
  modelstore: ./models
