server:
  port: 8083
  https:
    cert:   # /ssl/tls.crt
    key:    # /ssl/tls.key
  cors-origins:
    - http://localhost
    - https://instill-inc.tech
    - https://instill.tech
database:
  username: postgres
  password: password
  host: localhost
  port: 5432
  name: model
  version: 1
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 30
    connlifetime: 30 # In minutes
tritonserver:
  grpcuri: localhost:8001
  modelstore: ./model-repository
