from enum import Enum


class Task(Enum):
    TASK_CLASSIFICATION = 1
    TASK_DETECTION = 2
    TASK_KEYPOINT = 3
    TASK_OCR = 4
    TASK_INSTANCE_SEGMENTATION = 5
    TASK_SEMANTIC_SEGMENTATION = 6
    TASK_TEXT_TO_IMAGE = 7
    TASK_TEXT_GENERATION = 8
    TASK_IMAGE_TO_IMAGE = 9
    TASK_SPEECH_RECOGNITION = 10
