name: Add Issue to Project

on:
  issues:
    types:
      - opened

jobs:
  track_issue:
    uses: instill-ai/meta/.github/workflows/add-issue-to-prj.yml@main
    with:
      project_number: 11 # Instill Model project
    secrets:
      botGitHubToken: ${{ secrets.botGitHubToken }}
