name: Add PR to Project

on:
  pull_request_target:
    types:
      - opened

jobs:
  track_pr:
    uses: instill-ai/meta/.github/workflows/add-pr-to-prj.yml@main
    with:
      project_number: 11 # Instill Model project
    secrets:
      botGitHubToken: ${{ secrets.botGitHubToken }}
