name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .env

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - uses: actions/checkout@v4

      - name: Generate coverage report
        run: |
          go test -race ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
