name: Build and Push Test Images

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - "assets/model-**"

jobs:
  build-push-test-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model:
          [
            "dummy-cls",
            "dummy-det",
            "dummy-image-to-image",
            "dummy-instance-segmentation",
            "dummy-keypoint",
            "dummy-semantic-segmentation",
            "dummy-text-generation",
            "dummy-text-generation-chat",
            "dummy-text-to-image",
            "dummy-visual-question-answering",
          ]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.botGitHubToken }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Instill Python SDK
        run: pip install --pre instill-sdk

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: builder
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: dropletbot
          password: ${{ secrets.botDockerHubPassword }}

      - name: Build test models
        working-directory: ./assets/model-${{ matrix.model }}
        run: instill_build -t test

      - name: Push test models
        working-directory: ./assets/model-${{ matrix.model }}
        run: instill_push -t test -u docker.io
